// let ui = ...

const svgNS = "http://www.w3.org/2000/svg"

// TODO: Improve user experience of consuming JS objects generated by the JS emitter

function create_svg_elem(elem) {
  switch (elem.variant) {
    case tag_indexes.Line: {
      const line = document.createElementNS(svgNS, "line")
      line.setAttribute("x1", elem.paylaod.field0)
      line.setAttribute("y1", elem.paylaod.field1)
      line.setAttribute("x2", elem.paylaod.field2)
      line.setAttribute("y2", elem.paylaod.field3)
      line.setAttribute("stroke-width", elem.payload.field4)
      line.setAttribute("stroke", elem.payload.field5)
      return line
    }
  }
}

function create_html_elem(elem) {
  switch (elem.variant) {
    case tag_indexes.Button: {
      const button = document.createElement("button")
      button.onclick = () => {
        ui = elem.payload.field1()
        render_ui()
      }
      for (const child of elem.payload.field0) {
        button.appendChild(create_html_elem(child))
      }
      return button
    }
    case tag_indexes.Div: {
      const div = document.createElement("div")
      div.setAttribute("style", elem.payload.field0)
      for (const child of elem.payload.field1) {
        div.appendChild(create_html_elem(child))
      }
      return div
    }
    case tag_indexes.Text: {
      return document.createTextNode(elem.payload)
    }
    case tag_indexes.Svg: {
      const svg = document.createElementNS(svgNS, "svg")
      svg.setAttribute("style", elem.payload.field0)
      svg.setAttribute("viewBox", `0 0 ${elem.payload.field1} ${elem.payload.field2}`)
      for (const child of elem.payload.field3) {
        svg.appendChild(create_svg_elem(child))
      }
      return svg
    }
  }
}

function render_ui() {
  document.body.innerHTML = ""
  document.title = ui.field0
  for (const elem of ui.field1) {
    document.body.appendChild(create_html_elem(elem))
  }
}

window.onkeydown = (e) => {
  ui = ui.field2({field0: e.key})
  render_ui()
}

window.onload = () => {
  render_ui()
}
