// let state = ...

const svgNS = "http://www.w3.org/2000/svg"

// TODO: Improve user experience of consuming JS objects generated by the JS emitter

function create_svg_elem(elem) {
  switch (elem.variant) {
    case tag_indexes.Line: {
      const line = document.createElementNS(svgNS, "line")
      line.setAttribute("x1", elem.paylaod.field0)
      line.setAttribute("y1", elem.paylaod.field1)
      line.setAttribute("x2", elem.paylaod.field2)
      line.setAttribute("y2", elem.paylaod.field3)
      line.setAttribute("stroke-width", elem.payload.field4)
      line.setAttribute("stroke", elem.payload.field5)
      return line
    }
  }
}

function create_html_elem(elem) {
  switch (elem.variant) {
    case tag_indexes.Button: {
      const button = document.createElement("button")
      button.onclick = () => {
        state = elem.payload.field1
        render_ui()
      }
      for (const child of elem.payload.field0) {
        button.appendChild(create_html_elem(child))
      }
      return button
    }
    case tag_indexes.Div: {
      const div = document.createElement("div")
      div.setAttribute("style", elem.payload.field0)
      for (const child of elem.payload.field1) {
        div.appendChild(create_html_elem(child))
      }
      return div
    }
    case tag_indexes.Text: {
      return document.createTextNode(elem.payload)
    }
    case tag_indexes.Span: {
      const span = document.createElement("span")
      span.appendChild(document.createTextNode(elem.payload))
      return span
    }
    case tag_indexes.Svg: {
      const svg = document.createElementNS(svgNS, "svg")
      svg.setAttribute("style", elem.payload.field0)
      svg.setAttribute("viewBox", `0 0 ${elem.payload.field1} ${elem.payload.field2}`)
      for (const child of elem.payload.field3) {
        svg.appendChild(create_svg_elem(child))
      }
      return svg
    }
    case tag_indexes.Br: {
      return document.createElement("br")
    }
    case tag_indexes.Select: {
      const select = document.createElement("select")
      for (const [i, o] of elem.payload.field1.entries()) {
        const option = document.createElement("option")
        option.setAttribute("value", i)
        option.appendChild(document.createTextNode(o.field0))
        select.appendChild(option)
      }
      select.setAttribute("style", elem.payload.field0)
      select.onchange = () => {
        state = elem.payload.field1[select.value].field1
        render_ui()
      }
      return select
    }
  }
}

let global_state_string = localStorage.getItem("global-state")
if (global_state_string != null) {
  state.field0 = JSON.parse(global_state_string)
}
let ui = null

function render_ui() {
  const now = Date.now()
  // TODO: Sync global state across multiple instances of the website
  localStorage.setItem("global-state", JSON.stringify(state.field0))
  ui = state.field1(state.field0, {field0: {field0: now}})
  document.body.innerHTML = ""
  document.title = ui.field0
  for (const elem of ui.field1) {
    document.body.appendChild(create_html_elem(elem))
  }
}

window.onkeydown = (e) => {
  state = ui.field2({field0: e.key})
  render_ui()
}

window.onload = () => {
  render_ui()
}
