name: Build

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: write

# TODO: Add builds for mac (darwin)
jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
    - name: "Checkout code"
      uses: actions/checkout@v5
    - name: "Generate build artifact"
      run: ./docker-build.sh
    - name: "Possibly publish release"
      # If the last commit message is like `vMAJOR.MINOR.PATCH`, then create a stable release with that version
      run: |
        commit_message="$(echo "${{ github.event.head_commit.message }}" | head -1)"
        if [[ ${commit_message} =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
          echo "Publishing stable release because the latest commit message is ${commit_message}"
          gh release create "${commit_message}" ./gitignore_docker_build/* --target main
        else
          echo "Not publishing stable release because the latest commit message is ${commit_message}"
        fi
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
